version: '3'
services:
  server:
    build: .
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=cindh
      - MYSQL_ROOT_PASSWORD=salma
      - MYSQL_USER=salma
      - MYSQL_PASSWORD=salma
    ports:
      - 3307:3306
