server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springlog
    username: root
    password: chama2390

  jpa:
    hibernate:
      ddl-auto: update

  security:
    ignored: /**
    basic:
      enabled: false

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      static-path-pattern: /resources/**

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

